spring:

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: ENC(KjcjtVjALgdmmDrLO2o7TA==) #Itg77bWtnrs2oeR1WgQWRR319yZrqaVGlIwA4e9Ka10=
      port: 6379
      password: ENC(18N0c53bSm/+PyNYAAOzx8g2xk6k67oy) #cAV37F+FL3IUpEFNaq367sJN+c36j4oB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(/OFOD6/nWsL2FkdSezUldw==) #5UCG8P9Sad6Oyv5kecZrwn/U87qooIo+
    password: ENC(HfdJW9kILnplEREOCHSqtQ6MTXkWUDwj) #5UCG8P9Sad6Oyv5kecZrwn/U87qooIo+
    url: ENC(lKkLPeYyMkOMNMh39Bru1jhScwCRv6P5jv1CX7qPWEbsDzRt3RaS5sHS1CkYtCIt9ErVlh4+NezYJzwv3S59xQ1JbIPECaInlidY3fWOf3xaNSjIJuz629KyEUl3PhKrG+8xZ4Q4yTC9Jspr/bVGfg==)
    #DJe1+vNLc9cScQ5N4JKow1YRNV/jDA/n5UZ0fg+Ec/2YRk5lUe1s3wOM0fnw9vIxl213L6O/kkSaECq4uBBrNG7j7zrgaE1qbmK3JH0rChc0H5HruwUkvOoUfbVWtWfQulIpRkHtU4/6nMCd5e7Hjw==

#server:
#  port: 8080
#  servlet:
#    context-path: /api
