spring:

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: ENC(NlaOnFEohOhLwfm3BQKYzQxJYtI72xNO)
      port: 6379
      password: ENC(cAV37F+FL3IUpEFNaq367sJN+c36j4oB)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(5UCG8P9Sad6Oyv5kecZrwn/U87qooIo+)
    password: ENC(5UCG8P9Sad6Oyv5kecZrwn/U87qooIo+)
    url: ENC(DJe1+vNLc9cScQ5N4JKow1YRNV/jDA/n5UZ0fg+Ec/2YRk5lUe1s3wOM0fnw9vIxl213L6O/kkSaECq4uBBrNG7j7zrgaE1qbmK3JH0rChc0H5HruwUkvOoUfbVWtWfQulIpRkHtU4/6nMCd5e7Hjw==)

server:
  port: 8080
  servlet:
    context-path: /api
